---
title: "NGDR"
output: html_notebook
---
NGDR is the ratio of the net displacement (linear distance between starting point and end point of a path) to the gross displacement (total distance travelled) for each path recorded. 


Calculate Total distance of track
```{r}
library(dplyr)
head(Feeding)

total.dist <- function(x,y) {
  sum(sqrt((x-lag(x))^2+(y-lag(y))^2),na.rm=TRUE)
}

res <- Feeding %>% group_by(D_V_T) %>% summarise(dtot=total.dist(xsmooth,ysmooth))

print(res)

NGDR <- merge(AGG_Feed, res)

head(NGDR)

write.csv(NGDR, file = "~/Post-doc/Data/NGDR Sep 29 2023.csv", row.names = FALSE)


```


Calculate distance from start x,y to end, x,y location
```{r}
full_dist <- data.frame()
for (dvt in unique(Feeding$D_V_T)) {
  data1 <- Feeding %>% subset(D_V_T==dvt)
    sd1 <- data1[1,"smooth.d"]
    sd2 <- data1[5000,"smooth.d"]
    diff.dist <- sd1-sd2
    tmp <- data.frame(D_V_T=dvt,i,sd1,sd2,diff.dist)
    full_dist <- rbind(full_dist,tmp)
    print(dvt)
}


str(full_dist)
NGDR2 <- na.omit(NGDR2)
full_dist %>% group_by(D_V_T) %>% summarise_at(vars(diff.dist), mean)

NGDR2 <- merge(NGDR, full_dist)

head(NGDR2)
tail(NGDR2)

write.csv(NGDR2, file = "~/Post-doc/Data/NGDR Sep 29 2023.csv", row.names = FALSE)

```

Calculate NGDR ratio
```{r}
NGDR2$NGDR <- NGDR2$diff.dist/NGDR2$dtot
head(NGDR2)

range(NGDR2$diff.dist)

NGDR2 %>% group_by(Light, Flow.rate, Chem) %>% summarise_at(vars(NGDR, diff.dist, dtot), mean)
```


Plotting Angular data into histograms on polar projection
```{r}
## redo with vertical headings, change range for turn angles?

library(ggplot2)
head(AGG_Feed)
str(AGG_Feed)
range(AGG_Feed$turn.anglexysmooth)
AGG_Feed$turn.anglexysmooth <- AGG_Feed$turn.anglexysmooth/(2*pi)*360
f_mu <- mean(Feeding$turn.angle.smooth, by =c(Chem, Light, Flow.rate))

ggplot(AGG_Feed, aes(turn.anglexysmooth, fill = Chem)) +
  geom_histogram(binwidth = 5, boundary = 0, colour = "black", size = .25) +
  coord_polar() +
   ylim(0, 12)  +
  scale_x_continuous(limits = c(0,360),
                     breaks = seq(0, 360, by = 45),
                     minor_breaks = seq(0, 360, by = 15))+
  theme(axis.text=element_text(color="black"))+
  theme(axis.text.x=element_text(angle=0,hjust=1,vjust=0.4))+
  theme(axis.line = element_line(size = 0.5, linetype = "solid",
                                   colour = "black"))+
  theme(legend.key = element_rect(fill = "white"))+
  ##geom_vline(aes(heading.pi), xintercept = f_mu)+   ## adds mean angle line to plot
  labs(size = "", x = "Turn Angle (degrees)", y = "Frequency of Turn Angle", title = "")+
  scale_fill_manual(values=c("white", "gray", "gray35"),name = "Chemical Cue",
                    labels=c("Ambient", "Guano", "Guano+CHL"))+
 facet_grid(facets = Light ~ Flow.rate, labeller = label_both)





```
