---
title: "Cross-correlation, Nick version"
output: html_notebook
---



```{r}

# This is a work in progress....
rm(list=ls(all=TRUE))

#load("C:\\Users\\Nicole Hellessey\\Documents\\Post-doc\\Data\\Total Merged Data File (July 12 2022).Rdata")
#load('~/Work/Data/Antarctic/Total Merged Data File (July 11 2022).RData')
load('~/Work/Data/Antarctic/CC.TotalData.2022.07.20.RData')

head(TotalData) ## all rows of data from TotalData
head(CC.TotalData) ## ONLY complete cases of TotalData


library(ggplot2)
library(GGally)

flow.rate <- 0  # 0 0.6 3 5.9 8.9
chlorophyll <- 0 # 0 4.3 4.6 5.5 6.1 7.6 13.5 19
guano <- 1 # Absent=1 Present=2
light <- 2 # Absent=1 Present=2

velocity <- CC.TotalData$v[
  (CC.TotalData$Flow.rate==flow.rate & 
     CC.TotalData$Chlorophyll==chlorophyll & 
     as.numeric(CC.TotalData$Guano)==guano &
     as.numeric(CC.TotalData$Light)==light)]
plot(log10(velocity[1:length(x)-1]),log10(velocity[2:length(x)]),
     pch = 20,
  cex = 1.2,
  col = rgb(0, 0, 0.2, .1))

C <- NA
chls <- as.numeric(as.character(unique(CC.TotalData$Chlorophyll)))
for (i in 1:length(chls))
{
  chlorophyll <- (chls[i])
  velocity <- CC.TotalData$v[
  (CC.TotalData$Flow.rate==flow.rate & 
     CC.TotalData$Chlorophyll==chlorophyll & 
     as.numeric(CC.TotalData$Guano)==guano &
     as.numeric(CC.TotalData$Light)==light)]
  if (length(velocity) <= 1) {
    C[i] <- NA } else {
      c<-cor.test(log10(velocity[1:length(x)-1]),
                  log10(velocity[2:length(x)]))
      C[i] <- c$estimate}
}
  



ggpairs(CC.TotalData[
  (CC.TotalData$Flow.rate==flow.rate & 
     CC.TotalData$Chlorophyll==chlorophyll & 
     as.numeric(CC.TotalData$Guano)==guano &
     as.numeric(CC.TotalData$Light)==light),],
  columns = c(21,22,23,26,27,28))

plot(log10(CC.TotalData[
  (CC.TotalData$Flow.rate==flow.rate & 
     CC.TotalData$Chlorophyll==chlorophyll & 
     as.numeric(CC.TotalData$Guano)==guano &
     as.numeric(CC.TotalData$Light)==light),21]),
  (CC.TotalData[
  (CC.TotalData$Flow.rate==flow.rate & 
     CC.TotalData$Chlorophyll==chlorophyll & 
     as.numeric(CC.TotalData$Guano)==guano &
     as.numeric(CC.TotalData$Light)==light),22]))

plot((CC.TotalData[
  (CC.TotalData$Flow.rate==flow.rate & 
     CC.TotalData$Chlorophyll==chlorophyll & 
     as.numeric(CC.TotalData$Guano)==guano &
     as.numeric(CC.TotalData$Light)==light),22]),
  (CC.TotalData[
  (CC.TotalData$Flow.rate==flow.rate & 
     CC.TotalData$Chlorophyll==chlorophyll & 
     as.numeric(CC.TotalData$Guano)==guano &
     as.numeric(CC.TotalData$Light)==light),23]),
  pch = 20,
  cex = 1.2,
  col = rgb(0, 0, 0.2, .1))

ggpairs(CC.TotalData[
  (CC.TotalData$Flow.rate==flow.rate & 
     CC.TotalData$Chlorophyll==chlorophyll),],
  columns = c(21,22,23,26,27,28))

ggpairs(CC.TotalData[60000:120000,], columns = c(21, 22, 23, 26, 27, 28))

## look at cross correlation with specific variables?
ggpairs(ChlA0[700000:750000,], columns = c(21, 22, 23, 26, 27))  ### 0 chlorophyll data

ggpairs(g1[60000:120000,], columns = c(21, 22, 23, 26, 27))      ### Guano present data

### looking at specific pairs

ggplot(CC.TotalData[10000:20000,], aes(abs(pitch), abs(turn.angle-90))) +   ### weird pattern ??
  geom_point(alpha = 0.7)

ggplot(CC.TotalData[10000:20000,], aes(heading, turn.angle)) +     ### no pattern (good :) )
  geom_point(alpha = 0.7)


ggplot(CC.TotalData[10000:20000,], aes(vel.turn.angle, turn.angle)) +      #### pattern, linear regression??
  geom_point(alpha = 0.7)

```
Auto correlation


```{r}
################

#### auto correlation vs values vs lag(2) etc

library(tseries)
### acf - auto correlation function

par(mar= c(2,2,4,2))

acf(CC.TotalData$turn.angle[seq(1,10000,30)])  ##sinusoidal (statistical reason for it)

acf(CC.TotalData$vel.turn.angle[seq(1,10000,30)])   ##sinusoidal (statistical reason for it)

acf(CC.TotalData$vel.flow[seq(1,10000,30)])

acf(CC.TotalData$pitch[seq(1,10000,30)])

acf(CC.TotalData$heading[seq(1,10000,30)])

acf(CC.TotalData$v[seq(1,10000,30)])

acf(CC.TotalData$d[seq(1,10000,30)])

####################################################################################################################

acf(CC.TotalData$vx[seq(1,10000,30)])   #### need to look into this more

acf(CC.TotalData$vy[seq(1,10000,30)]) 

acf(CC.TotalData$vz[seq(1,10000,30)]) 

acf(CC.TotalData$dx[seq(1,10000,30)])    #### need to look into this more

acf(CC.TotalData$dy[seq(1,10000,30)]) 

acf(CC.TotalData$dz[seq(1,10000,30)]) 

####################################################################################################################


###   Do we need to look at acf across variables as well?
```



